app/aws/__init__.py
from flask import Blueprint

aws = Blueprint('aws', __name__, url_prefix='/aws')
from app.aws import routes

app/aws/routes.py
from flask import render_template, flash, redirect, url_for, request
from ..database.db import get_all_users, create_user, set_user_profile_picture_file_names
from .Create_Collection import create, list_collections, delete
from ..uploads.file_handler import is_file_type_allowed, upload_file_to_s3
from werkzeug.utils import secure_filename
import os
from config import Config
import io
from PIL import Image, ImageDraw, ExifTags, ImageColor, ImageFont
from .Register_Faces import add_face_to_collection 
from .Face_recognize import face_recognition_saving_image
from app.aws import aws
from app import app
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])

@aws.route("/s3", methods=['GET'])
def home():    
    users = get_all_users()
    return render_template('aws/s3page.html', users=users)


@aws.route("/sign-up-new-user", methods=['POST'])
def sign_up_new_user():
    name = request.form['name']
    create_user(name)
    return redirect(url_for('aws/s3page.html'))


@aws.route("/upload-image/<user_id>", methods=['POST'])
def upload_image(user_id):
    if 'file' not in request.files:
        flash('No file uploaded', 'danger')
        return redirect(url_for('aws/s3page.html'))
    
    file_to_upload = request.files['file']

    if file_to_upload.filename == '':
        flash('No file uploaded', 'danger')
        return redirect(url_for('aws/s3page.html'))
    
    if file_to_upload and is_file_type_allowed(file_to_upload.filename):
        provided_file_name = secure_filename(file_to_upload.filename)
        stored_file_name = upload_file_to_s3(file_to_upload, provided_file_name)
        set_user_profile_picture_file_names(user_id, stored_file_name, provided_file_name)
        flash(f'{provided_file_name} was successfully uploaded', 'success')
    
    return redirect(url_for('aws/s3page.html'))

### 
@aws.route('/reko1')
def start_page():
    return render_template('aws/reko_index.html')

@aws.route('/collection')
def collection_page():
    count,lst=list_collections()
    return render_template(('aws/collection.html'), count=count, lst=lst)


@aws.route('/create_page', methods=['POST'])
def create_page():
    COLLECTION_NAME = str(request.form['collection-name'])
    COLLECTION_NAME=COLLECTION_NAME.strip()
    print(COLLECTION_NAME)
    statement=create(COLLECTION_NAME)
    print(statement)
    count,lst=list_collections()
    return render_template('aws/collection.html', count=count, lst=lst, statement=statement)


@aws.route('/delete_page')
def delete_page():
    COLLECTION_NAME=request.args.get('name')
    statement=delete(COLLECTION_NAME)
    count,lst=list_collections()
    return render_template('aws/collection.html', count=count, lst=lst, statement=statement)


@aws.route('/register_faces')
def register_page_reko():
    count,lst=list_collections()
    return render_template('aws/reko_register.html', lst=lst)

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

@aws.route('/register_faces', methods=['POST'])
def register_faces():
    if 'file' not in request.files:
        statement='No file part'
        count, lst = list_collections()
        return render_template('aws/reko_register.html', lst=lst,statement=statement)
    file = request.files['file']
    if file.filename == '':
        statement='No image selected for uploading'
        count, lst = list_collections()
        return render_template('aws/reko_register.html', lst=lst, statement=statement)
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
        Register_image = Image.open('static/uploads/' + filename)
        print(Register_image)
        bytes_array = io.BytesIO()
        Register_image.save(bytes_array, format="PNG")
        source_image_bytes = bytes_array.getvalue()
        name = str(request.form['person-name'])
        name = name.strip()
        COLLECTION_NAME=request.form['collection']
        print(name)
        print(COLLECTION_NAME)
        count, lst = list_collections()
        registration_result = add_face_to_collection(source_image_bytes, name, COLLECTION_NAME)
        #print('upload_image filename: ' + filename)
        # flash('Image successfully uploaded and displayed below')
        return render_template('aws/reko_register.html', lst=lst, reg_lst=registration_result, filename=filename)
    else:
        statement='Allowed image types are -> png, jpg, jpeg, gif'
        count, lst = list_collections()
        return render_template('aws/reko_register.html', lst=lst, statement=statement)

@aws.route('/display/<filename>')
def display_image(filename):
    #print('display_image filename: ' + filename)
    return redirect(url_for('static', filename='uploads/' + filename), code=301)

@aws.route('/display/<filename>')
def display_image_recognition(filename):
    #print('display_image filename: ' + filename)
    return redirect(url_for('static', filename='result/' + filename), code=301)

@aws.route('/recognize_page')
def recognize_page():
    count,lst=list_collections()
    return render_template('aws/recognize.html', lst=lst)

@aws.route('/recognize_faces', methods=['POST'])
def recognize_faces():
    if 'file' not in request.files:
        statement='No file part'
        count, lst = list_collections()
        return render_template('aws/recognize.html', lst=lst,statement=statement)
    file = request.files['file']
    if file.filename == '':
        statement='No image selected for uploading'
        count, lst = list_collections()
        return render_template('recognize.html', lst=lst, statement=statement)
    if file and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
        Register_image = Image.open('static/uploads/' + filename)
        print(Register_image)

        COLLECTION_NAME=request.form['collection']
        print(COLLECTION_NAME)
        count, lst = list_collections()

        path="result/"+filename
        result_img,res_lst = face_recognition_saving_image(Register_image, COLLECTION_NAME)
        result_img.save('static/'+path)

        #print('upload_image filename: ' + filename)
        # flash('Image successfully uploaded and displayed below')
        return render_template('aws/recognize.html', lst=lst, filename=path,res_lst=res_lst)
    else:
        statement='Allowed image types are -> png, jpg, jpeg, gif'
        count, lst = list_collections()
        return render_template('aws/recognize.html', lst=lst, statement=statement)

@aws.after_request
def add_header(response):
    response.headers['Pragma'] = 'no-cache'
    response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
    response.headers['Expires'] = '0'
    return response

app/templates/aws/collection.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Collection</title>
    <style>
      .hidden {
        display: none;
      }
    </style>
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.css"
      rel="stylesheet"
    />
  </head>
  <body onload="hideLoadingDiv()">
    <div class="p-4">
      <h3 class="text-center text-white mb-4 my-2 p-4 bg-primary card">
        Face Recognition using Amazon Rekognition
      </h3>
      <div class="text-right">
        <button
          style="float: right"
          type="button"
          class="mx-auto btn btn-primary text-nowrap"
          onclick="window.location.href='{{ url_for( 'aws.start_page') }}'"
        >
          Go Back to Home
        </button>
      </div>
      <br /><br />

      <div class="bg-light border border-info my-2 p-4 card">
        <div>
          <h4 style="float: left" class="m-0 p-0">About Collection</h4>
          <br />
          <br />
          <small style="float: left" class="text-muted"
            >You can create collection or you can delete collection in this
            page</small
          >
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-md-6 col-lg-6 border p-4">
          <div class="text-center">
            <button
              style="width: 100%"
              type="button"
              class="mx-auto btn btn-primary text-nowrap"
              onclick="window.location.href='{{ url_for( 'aws.register_page_reko') }}'"
            >
              Go for Register faces
            </button>
          </div>
        </div>
        <div class="col-12 col-md-6 col-lg-6 border p-4">
          <div class="text-center">
            <button
              style="width: 100%"
              type="button"
              class="mx-auto btn btn-primary text-nowrap"
              onclick="window.location.href='{{ url_for( 'aws.register_faces') }}'"
            >
              Go for Recognize Facesssss
            </button>
          </div>
        </div>
      </div>
      {% if statement %}
      <div class="text-center" id="LOADING">
        <br />
        <button
          style="width: 100%"
          type="submit"
          class="mx-auto btn btn-warning text-wrap"
        >
          {{ statement }}
        </button>
      </div>
      <br />
      {% endif %}
      <div class="row">
        <div class="col-12 col-md-4 col-lg-4 border p-4">
          <div>
            <form id="todo-form" action="/create_page" method="post">
              <input
                id="collection-name"
                name="collection-name"
                placeholder="Enter Collection Name"
                class="form-control"
                required
              /><br />
              <br />
              <div class="text-center">
                <button
                  type="submit"
                  class="mx-auto btn btn-primary text-nowrap"
                >
                  Create Collection
                </button>
              </div>
            </form>
          </div>
        </div>

        <div class="col-12 col-md-8 col-lg-8 border rounded p-4" id="todo_list">
          <h3 class="text-center text-muted mb-3">List of Collection</h3>
          <small style="float: right" class="text-muted"
            >Total count {{ count }}</small
          >
          <br />

          {% for item in lst %}
          <div
            id="{{ item }}"
            class="todo-item my-2 p-4 bg-light border border-light card"
          >
            <div class="">
              <h4 style="float: left" class="m-0 p-0">{{ item }}</h4>
              <div style="float: right">
                <i
                  style="cursor: pointer"
                  onclick="window.location.href='{{ url_for( 'aws.delete_page'), name_item }}'"
                  class="fas text-danger fa-trash"
                ></i>
              </div>
            </div>
            <small class="text-muted">collection name</small>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <!-- MDB -->
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.js"
    ></script>
    <script>
      function hideLoadingDiv() {
        setTimeout(function () {
          document.getElementById("LOADING").classList.add("hidden");
        }, 5000);
      }
    </script>
    <script type="text/javascript">
      window.history.forward();
      function noBack() {
        window.history.forward();
      }
    </script>
  </body>
</html>

app/templates/aws/recognize.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Recognition</title>
    <style>
      .hidden {
        display: none;
      }
    </style>
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="p-4">
      <h3 class="text-center text-white mb-4 my-2 p-4 bg-primary card">
        Face Recognition using Amazon Rekognition
      </h3>
      <div class="text-right">
        <button
          style="float: right"
          type="button"
          class="mx-auto btn btn-primary text-nowrap"
          onclick="window.location.href='{{ url_for( 'aws.start_page') }}'"
        >
          Go Back to Home
        </button>
      </div>
      <br /><br />
      <div class="bg-light border border-info my-2 p-4 card">
        <div>
          <h4 style="float: left" class="m-0 p-0">
            About Recognition of Faces
          </h4>
          <br />
          <br />
          <small style="float: left" class="text-muted"
            >You Need to select collection in which you want to recognize faces
            and also you need to upload person's image to recognize</small
          >
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-md-6 col-lg-6 border p-4">
          <div class="text-center">
            <button
              style="width: 100%"
              type="button"
              class="mx-auto btn btn-primary text-nowrap"
              onclick="window.location.href='{{ url_for( 'aws.collection_page') }}'"
            >
              Go for Creating/Deleting collection
            </button>
          </div>
        </div>
        <div class="col-12 col-md-6 col-lg-6 border p-4">
          <div class="text-center">
            <button
              style="width: 100%"
              type="button"
              class="mx-auto btn btn-primary text-nowrap"
              onclick="window.location.href='{{ url_for( 'aws.register_page_reko') }}'"
            >
              Go for Register Faces
            </button>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-12 col-md-4 col-lg-4 border p-4">
          <div>
            <form
              id="todo-form"
              action="/recognize_faces"
              method="post"
              enctype="multipart/form-data"
            >
              Select a Collection &nbsp;&nbsp;&nbsp;&nbsp;
              <select name="collection" required>
                {% for item in lst %}
                <option value="{{item}}">{{item}}</option>
                {% endfor %}
              </select>
              <br /><br />
              <input type="file" name="file" autocomplete="off" required />
              <br />
              <br />
              <div class="text-center">
                <button
                  type="submit"
                  class="mx-auto btn btn-primary text-nowrap"
                >
                  Recognize Faces
                </button>
              </div>
            </form>

            <br />
            {% for item in res_lst %}
            <div
              id="{{ item }}"
              class="todo-item my-2 p-4 bg-dark border border-light card"
            >
              <h10 style="float: left" class="text-white m-0 p-0"
                >{{ item }}</h10
              >
            </div>
            {% endfor %}
          </div>
        </div>

        <div class="col-12 col-md-8 col-lg-8 border rounded p-4" id="todo_list">
          {% if filename %}
          <div style="height: 310px">
            <img
              style="width: 100%; height: 100%"
              src="{{url_for('static',filename = filename)}}"
            />
          </div>
          {% endif %}
        </div>
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <!-- MDB -->
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.js"
    ></script>
    <script type="text/javascript">
      window.history.forward();
      function noBack() {
        window.history.forward();
      }
    </script>
  </body>
</html>

app/templates/aws/reko_index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Face Recognition</title>

    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="p-4">
      <h3 class="text-center text-white mb-4 my-2 p-4 bg-primary card">
        Face Recognition using Amazon Rekognition
      </h3>

      <div class="row p-4">
        <h4 class="text-center text-white mb-4 my-2 p-4 bg-success card">
          Steps to Follow
        </h4>
        <div class="bg-light border border-info my-2 p-4 card">
          <div>
            <h4 style="float: left" class="m-0 p-0">Create Collection</h4>
            <button
              style="float: right"
              id="collection"
              type="button"
              class="mx-auto btn btn-primary text-nowrap"
              onclick="window.location.href='{{ url_for( 'aws.collection_page') }}'"
            >
              Go
            </button>
            <br />
            <br />
            <small style="float: left" class="text-muted"
              >If you don't have a collection click on Go button and create
              collection. And also you can check created collection by clicking
              same button</small
            >
          </div>
        </div>

        <div class="bg-light border border-info my-2 p-4 card">
          <div>
            <h4 style="float: left" class="m-0 p-0">Register Faces</h4>
            <button
              style="float: right"
              id="register"
              type="button"
              class="mx-auto btn btn-primary text-nowrap"
              onclick="window.location.href='{{ url_for( 'aws.register_page_reko') }}'"
            >
              Go
            </button>
            <br />
            <br />
            <small style="float: left" class="text-muted"
              >If you want to Register particular person's Face then click on Go
              button</small
            >
          </div>
        </div>

        <div class="bg-light border border-info my-2 p-4 card">
          <div>
            <h4 style="float: left" class="m-0 p-0">Recognize Faces</h4>
            <button
              style="float: right"
              id="recognize"
              type="button"
              class="mx-auto btn btn-primary text-nowrap"
              onclick="window.location.href='{{ url_for( 'aws.recognize_page') }}'"
            >
              Go
            </button>
            <br />
            <br />
            <small style="float: left" class="text-muted"
              >If you want to start Recognize faces you click on go button and
              you can start recognition</small
            >
          </div>
        </div>

        <div class="bg-light border border-info my-2 p-4 card">
          <img src="../static/images/flow.png" style="width: 100%" />
        </div>
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <!-- MDB -->
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.js"
    ></script>
    <script type="text/javascript">
      window.history.forward();
      function noBack() {
        window.history.forward();
      }
    </script>
  </body>
</html>

app/templates/aws/reko_register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Registration</title>
    <style>
      .hidden {
        display: none;
      }
    </style>
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.css"
      rel="stylesheet"
    />
  </head>
  <body onload="hideLoadingDiv()">
    <div class="p-4">
      <h3 class="text-center text-white mb-4 my-2 p-4 bg-primary card">
        Face Recognition using Amazon Rekognition
      </h3>
      <div class="text-right">
        <button
          style="float: right"
          type="button"
          class="mx-auto btn btn-primary text-nowrap"
          onclick="window.location.href='{{ url_for( 'aws.start_page') }}'"
        >
          Go Back to Home
        </button>
      </div>
      <br /><br />
      <div class="bg-light border border-info my-2 p-4 card">
        <div>
          <h4 style="float: left" class="m-0 p-0">
            About Registration of Faces
          </h4>
          <br />
          <br />
          <small style="float: left" class="text-muted"
            >You Need to select collection in which you want to register faces
            and also you need to enter the person name without space and Need to
            upload person's image to register</small
          >
        </div>
      </div>
      <div class="row">
        <div class="col-12 col-md-6 col-lg-6 border p-4">
          <div class="text-center">
            <button
              style="width: 100%"
              type="button"
              class="mx-auto btn btn-primary text-nowrap"
              onclick="window.location.href='{{ url_for( 'aws.collection_page') }}'"
            >
              Go for Creating/Deleting collection
            </button>
          </div>
        </div>
        <div class="col-12 col-md-6 col-lg-6 border p-4">
          <div class="text-center">
            <button
              style="width: 100%"
              type="button"
              class="mx-auto btn btn-primary text-nowrap"
              onclick="window.location.href='{{ url_for( 'aws.recognize_page') }}'"
            >
              Go for Recognize Faces
            </button>
          </div>
        </div>
      </div>
      {% if statement %}
      <div class="text-center" id="LOADING">
        <br />
        <button
          style="width: 100%"
          type="submit"
          class="mx-auto btn btn-warning text-nowrap"
        >
          {{ statement }}
        </button>
      </div>
      <br />
      {% endif %}
      <div class="row">
        <div class="col-12 col-md-8 col-lg-8 border p-4">
          <div>
            <form
              id="todo-form"
              action="/register_faces"
              method="post"
              enctype="multipart/form-data"
            >
              Select a Collection &nbsp;&nbsp;&nbsp;&nbsp;
              <select name="collection" required>
                {% for item in lst %}
                <option value="{{item}}">{{item}}</option>
                {% endfor %}
              </select>
              <br /><br />
              <input
                id="person-name"
                name="person-name"
                placeholder="Enter Person Name"
                class="form-control"
                required
              />
              <br />
              <input type="file" name="file" autocomplete="off" required />
              <br />
              <br />
              <div class="text-center">
                <button
                  type="submit"
                  class="mx-auto btn btn-primary text-nowrap"
                >
                  Register Faces
                </button>
              </div>
            </form>
          </div>
        </div>

        <div class="col-12 col-md-4 col-lg-4 border rounded p-4" id="todo_list">
          {% for item in reg_lst %}
          <div class="text-left bg-light card">
            <b style="width: 100%" class="text-dark">{{ item }}</b>
          </div>
          {% endfor %} {% if filename %}
          <div>
            <img
              style="width: 100%; height: 100%"
              src="{{ url_for('display_image', filename=filename) }}"
            />
          </div>
          {% endif %}
        </div>
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <!-- MDB -->
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.js"
    ></script>
    <script>
      function hideLoadingDiv() {
        setTimeout(function () {
          document.getElementById("LOADING").classList.add("hidden");
        }, 5000);
      }
    </script>
    <script type="text/javascript">
      window.history.forward();
      function noBack() {
        window.history.forward();
      }
    </script>
  </body>
</html>

app/templates/aws/s3page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <title>S3 Tutorial</title>
  </head>
  <body>
    <div class="row justify-content-center mt-5">
      <div class="col-6 align-self-center">
        <h1 class="text-primary">Flask S3</h1>

        <form
          method="post"
          action="{{ url_for('aws.sign_up_new_user') }}"
          class="form-inline my-4"
        >
          <div class="row">
            <h2>Create user</h2>
            <div class="form-group col-10">
              <input
                type="text"
                class="form-control"
                name="name"
                placeholder="Users name...."
              />
            </div>
            <div class="form-group col-2">
              <button type="submit" class="btn btn-primary">Create User</button>
            </div>
          </div>
        </form>

        {% with messages = get_flashed_messages(with_categories=true) %} {% if
        messages %} {% for category, message in messages %}
        <div class="alert alert-{{ category }} col-lg-12">{{ message }}</div>
        {% endfor %} {% endif %} {% endwith %}

        <table class="table">
          <thead>
            <tr>
              <th scope="col">Profile Pic</th>
              <th scope="col">User Id</th>
              <th scope="col">Name</th>
              <th scope="col">Upload Image</th>
            </tr>
          </thead>
          <tbody>
            {% for user in users %}
            <tr>
              <th>
                {% if user.provided_file_name and user.stored_file_name %}
                <img
                  style="max-height: 50px; max-width: 50px"
                  src="{{ user.get_profile_picture_url() }}"
                  class="rounded float-left"
                />
                {% else %}
                <p>No Image</p>
                {% endif %}
              </th>
              <td>{{ user.id }}</td>
              <td>{{ user.name }}</td>
              <td>
                <form
                  method="post"
                  enctype="multipart/form-data"
                  action='{{ url_for("aws.upload_image", user_id=user.id) }}'
                >
                  <div class="input-group">
                    <input
                      type="file"
                      class="form-control"
                      name="file"
                      aria-label="Upload"
                    />
                    <button class="btn btn-outline-secondary" type="submit">
                      Submit
                    </button>
                  </div>
                </form>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>