app/mysql/__init__.py
from flask import Blueprint
bp = Blueprint('mysql', __name__, url_prefix='/mysql')




from app.mysql import routes

app/mysql/routes.py
 
from flask import render_template, flash, redirect, url_for, request, g, session
from app.mysql import bp
from app import mysql
from flask_mysqldb import MySQL
import MySQLdb.cursors
import re
import MySQLdb


# mysql = MySQL()



@bp.route('/')
@bp.route('/login', methods =['GET', 'POST'])
def login():
    msg = ''
    if request.method == 'POST' and 'username' in request.form and 'password' in request.form:
        username = request.form['username']
        password = request.form['password']
        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM accounts WHERE username = % s AND password = % s', (username, password, ))
        account = cursor.fetchone()
        if account:
            session['loggedin'] = True
            session['id'] = account['id']
            session['username'] = account['username']
            msg = 'Logged in successfully !'
            return render_template('mysql/index.html', msg = msg)
        else:
            msg = 'Incorrect username / password !'
    return render_template('mysql/login.html', msg = msg)
 
@bp.route('/logout')
def logout():
   session.pop('loggedin', None)
   session.pop('id', None)
   session.pop('username', None)
   return redirect(url_for('mysql.login'))
 
@bp.route('/register', methods =['GET', 'POST'])
def register():
    msg = ''
    if request.method == 'POST' and 'username' in request.form and 'password' in request.form and 'email' in request.form and 'address' in request.form and 'city' in request.form and 'country' in request.form and 'postalcode' in request.form and 'organisation' in request.form:
        username = request.form['username']
        password = request.form['password']
        email = request.form['email']
        organisation = request.form['organisation'] 
        address = request.form['address']
        city = request.form['city']
        state = request.form['state']
        country = request.form['country']   
        postalcode = request.form['postalcode']
        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM accounts WHERE username = % s', (username, ))
        account = cursor.fetchone()
        if account:
            msg = 'Account already exists !'
        elif not re.match(r'[^@]+@[^@]+\.[^@]+', email):
            msg = 'Invalid email address !'
        elif not re.match(r'[A-Za-z0-9]+', username):
            msg = 'name must contain only characters and numbers !'
        else:
            cursor.execute('INSERT INTO accounts VALUES (NULL, % s, % s, % s, % s, % s, % s, % s, % s, % s)', (username, password, email, organisation, address, city, state, country, postalcode, ))
            mysql.connection.commit()
            msg = 'You have successfully registered !'
    elif request.method == 'POST':
        msg = 'Please fill out the form !'
    return render_template('mysql/register.html', msg = msg)
 
 
@bp.route("/index")
def index():
    if 'loggedin' in session:
        return render_template("mysql/index.html")
    return redirect(url_for('mysql/login'))
 
 
@bp.route("/display")
def display():
    if 'loggedin' in session:
        cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cursor.execute('SELECT * FROM accounts WHERE id = % s', (session['id'], ))
        account = cursor.fetchone()   
        return render_template("mysql/display.html", account = account)
    return redirect(url_for('mysql/login'))
 
@bp.route("/update", methods =['GET', 'POST'])
def update():
    msg = ''
    if 'loggedin' in session:
        if request.method == 'POST' and 'username' in request.form and 'password' in request.form and 'email' in request.form and 'address' in request.form and 'city' in request.form and 'country' in request.form and 'postalcode' in request.form and 'organisation' in request.form:
            username = request.form['username']
            password = request.form['password']
            email = request.form['email']
            organisation = request.form['organisation'] 
            address = request.form['address']
            city = request.form['city']
            state = request.form['state']
            country = request.form['country']   
            postalcode = request.form['postalcode']
            cursor = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
            cursor.execute('SELECT * FROM accounts WHERE username = % s', (username, ))
            account = cursor.fetchone()
            if account:
                msg = 'Account already exists !'
            elif not re.match(r'[^@]+@[^@]+\.[^@]+', email):
                msg = 'Invalid email address !'
            elif not re.match(r'[A-Za-z0-9]+', username):
                msg = 'name must contain only characters and numbers !'
            else:
                cursor.execute('UPDATE accounts SET  username =% s, password =% s, email =% s, organisation =% s, address =% s, city =% s, state =% s, country =% s, postalcode =% s WHERE id =% s', (username, password, email, organisation, address, city, state, country, postalcode, (session['id'], ), ))
                mysql.connection.commit()
                msg = 'You have successfully updated !'
        elif request.method == 'POST':
            msg = 'Please fill out the form !'
        return render_template("mysql/update.html", msg = msg)
    return redirect(url_for('mysql/login'))
 

app/templates/mysql/display.html
<!--Store this code in 'display.html' file inside the 'templates' folder-->
 
<html lang="en">
    <head>
        <title>display</title>
        <link rel="stylesheet" href="../static/style.css">
    </head>
    <body bgcolor="#e6ffee">
        <div class="one">
            <div class="two">
                <h1>Side Bar</h1>
                <ul>
                    <li><a href="{{url_for('mysql.index')}}">Index</a></li>
                    <li class="active"><a href="{{url_for('mysql.display')}}">Display</a></li>
                    <li><a href="{{url_for('mysql.update')}}">Update</a></li>
                    <li><a href="{{url_for('mysql.logout')}}">Log out</a></li>
                </ul>
            </div>
            <div class="content" align="center">
                <div class="topbar">
                    <h2>Welcome!! You are in Display Page!! </h2>                       
                </div>  </br>
                <div class="contentbar">
                    <h1>Your Details</h1>    </br>
                     {% block content %}
                        <div class="border">
                            <table class="worddark"></br></br></br></br>
                                <tr>
                                    <td>Username:</td>
                                    <td>{{ account['username'] }}</td>
                                </tr>
                                <tr>
                                    <td>Password:</td>
                                    <td>{{ account['password'] }}</td>
                                </tr>
                                <tr>
                                    <td>Email ID:</td>
                                    <td>{{ account['email'] }}</td>
                                </tr>
                                <tr>
                                    <td>Organisation:</td>
                                    <td>{{ account['organisation'] }}</td>
                                </tr>
                                <tr>
                                    <td>Address:</td>
                                    <td>{{ account['address'] }}</td>
                                </tr>
                                <tr>
                                    <td>City:</td>
                                    <td>{{ account['city'] }}</td>
                                </tr>
                                <tr>
                                    <td>State:</td>
                                    <td>{{ account['state'] }}</td>
                                </tr>
                                <tr>
                                    <td>Country:</td>
                                    <td>{{ account['country'] }}</td>
                                </tr> 
                                <tr>
                                    <td>Postal code:</td>
                                    <td>{{ account['postalcode'] }}</td>
                                </tr>                         
                            </table>
                        </div>
                    {% endblock %}                                          
                </div>
                 
            </div>
        </div>
    </body>
</html>

app/templates/mysql/index.html
<!--Store this code in 'index.html' file inside the 'templates' folder-->
<html lang="en">
    <head>
        <title>index</title>
        <link rel="stylesheet" href="../static/style.css">
    </head>
 
    <body bgcolor="#e6ffee">
        <div class="one">
            <div class="two">
                <h1>Side Bar</h1>
                <ul>
                    <li class="active"><a href="{{url_for('mysql.index')}}">Index</a></li>
                    <li><a href="{{url_for('mysql.display')}}">Display</a></li>
                    <li><a href="{{url_for('mysql.update')}}">Update</a></li>
                    <li><a href="{{url_for('mysql.logout')}}">Log out</a></li>
                </ul>
            </div>
            <div class="content" align="center">
                <div class="topbar">
                    <h2>Welcome!! You are in Index Page!! </h2>                       
                </div></br></br>
                <div class="contentbar">
                     <div class="msg">{{ msg }}</div>
                </div> 
                 
            </div>
        </div>
    </body>
</html>

app/templates/mysql/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../static/login.css" />

    <title>Login</title>
  </head>
  <body>
    <div class="center">
      <h1>Login</h1>
      <form
        action="{{ url_for('mysql.login')}}"
        method="post"
        autocomplete="off"
      >
        <div class="msg">{{ msg }}</div>
        <div class="txt_field">
          <input
            type="text"
            name="username"
            placeholder=""
            class="textbox"
            id="username"
            required
          />
          <span></span>
          <label>Username</label>
        </div>
        <div class="txt_field">
          <input
            type="password"
            name="password"
            placeholder=""
            class="textbox"
            id="password"
            required
          />
          <span></span>
          <label>Password</label>
        </div>
        <input type="submit" class="btn" value="Login" />
        <div class="signup_link">
          New to this page?
          <a class="worddark" href="{{ url_for('mysql.register')}}"
            >Register here</a
          >
        </div>
      </form>
    </div>
  </body>
</html>
<!--Store this code in 'login.html' file inside the 'templates' folder-->

<!-- <div class="center">
    <h1>Login</h1>
    <form method="post">
      <div class="txt_field">
      
        <input type="text" required> 
        <span></span>
        <label>Username</label>
      </div>
     
       <div class="txt_field">
        <input type="password" required> 
         <span></span>
         <label>Password</label>
         </div>
         <div class="pass">Forgot password?</div>
         <input type="submit" value="Login">
         <div class="signup_link">
           Not a member ? <a href="#"> Signup</a>
         </div>
           
      </div> -->

app/templates/mysql/register.html
<!--Store this code in 'register.html' file inside the 'templates' folder-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="../static/login.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> register </title>
</head>

<body>
    <div class="center">
        <div class="">
            <h1>Register</h1>
        </div></br></br>
          <form action="{{ url_for('mysql.register')}}" method="post" autocomplete="off">
          <div class="msg">{{ msg }}</div>
          <div class="txt_field">
            <input type="text" name="username" placeholder="" class="textbox" id="username" required>
                     <span></span>
            <label>Username</label>
          </div>
          <div class="txt_field">
            <input type="password" name="password" placeholder="" class="textbox" id="password" required>
            <span></span>
            <label>Password</label>
          </div>
          <div class="txt_field">

            <input type="email" name="email" placeholder="" class="textbox" id="email" required> 
            <span></span>
            <label>Email</label>
          </div>
          <div class="txt_field">
            <input type="text" name="organisation" placeholder="" class="textbox" id="organisation" required>
            <span></span>
            <label>Organisation</label>
          </div>
          <div class="txt_field">
            
            <input type="text" name="address" placeholder="" class="textbox" id="address" required>
            <span></span>
            <label>Address</label>
          </div>
          <div class="txt_field">

            <input type="text" name="city" placeholder="" class="textbox" id="city" required>
            <span></span>
            <label>City</label>
          </div>
          <div class="txt_field">
            <input type="text" name="state" placeholder="" class="textbox" id="state" required>
            <span></span>
            <label>State</label>
          </div>
          <div class="txt_field">
            <input type="text" name="country" placeholder="" class="textbox" id="country" required>
            <span></span>
            <label>Country</label>
          </div>
          <div class="txt_field">
            <input type="text" name="postalcode" placeholder="" class="textbox" id="postalcode" required>
            <span></span>
            <label>Postal Code</label>
          </div>
          <input type="submit" class="btn" value="Register">
          <div class="signup_link">Already have account? <a class="worddark" href="{{ url_for('mysql.login')}}">Login here</a></p>
          </div>
        </form>
    </div>
</body>
</html>

app/templates/mysql/update.html
<!--Store this code in 'update.html' file inside the 'templates' folder-->
<html lang="en">
    <head>
        <title>update</title>
        <link rel="stylesheet" href="../static/style.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Mulish&display=swap" rel="stylesheet">
    </head>
    <body bgcolor="#e6ffee">
        <div class="one">
            <div class="two">
                <h1>Side Bar</h1>
                <ul>
                    <li><a href="{{url_for('mysql.index')}}">Index</a></li>
                    <li><a href="{{url_for('mysql.display')}}">Display</a></li>
                    <li class="active"><a href="{{url_for('mysql.update')}}">Update</a></li>
                    <li><a href="{{url_for('mysql.logout')}}">Log out</a></li>
                </ul>
            </div>
            <div class="content" align="center">
                <div class="topbar">
                    <h2>Welcome!! You are in Update Page!! </h2>                       
                </div></br></br>
                <div class="contentbar">
                  <h1>Fill Your Details to Update</h1></br>
                    <form action="{{ url_for('mysql.update') }}" method="post" autocomplete="off" class="form">
                            <div class="msg">{{ msg }}</div>
                            <input type="text" name="username" placeholder="Enter Your Username" class="textbox" id="username" required></br></br>
                            <input type="password" name="password" placeholder="Enter Your Password" class="textbox" id="password" required></br></br>
                            <input type="email" name="email" placeholder="Enter Your Email ID" class="textbox" id="email" required></br></br>
                            <input type="text" name="organisation" placeholder="Enter Your Organisation" class="textbox" id="organisation" required></br></br>
                            <input type="text" name="address" placeholder="Enter Your Address" class="textbox" id="address" required></br></br>
                            <input type="text" name="city" placeholder="Enter Your City" class="textbox" id="city" required></br></br>
                            <input type="text" name="state" placeholder="Enter Your State" class="textbox" id="state" required></br></br>
                            <input type="text" name="country" placeholder="Enter Your Country" class="textbox" id="country" required></br></br>
                            <input type="text" name="postalcode" placeholder="Enter Your Postal Code" class="textbox" id="postalcode" required></br></br>
                            <input type="submit" class="btn" value="Update">
                    </form>                    
                </div> 
            </div>
        </div>
    </body>
</html>